### PR TITLE
Pushing files and added link in readme.md 

### PR DESCRIPTION
**Pull request by deeptikinger**

### CODE REVIEW

**Comment by WDI-IT** [comment]
Send me one of the product ids

**Comment by deeptikinger** [comment]
All product's Id with their respective title name

{"_id":{"$oid":"5eecc883dc95512f788de98b"},
"title":"Apple",


{"_id":{"$oid":"5eecc8d5dc95512f788de98c"},
"title":"Cake",

{"_id":{"$oid":"5eecc967dc95512f788de98d"},
"title":"Cat!!!!"

{"_id":{"$oid":"5eecc993dc95512f788de98e"},
"title":"Pen"

{"_id":{"$oid":"5eed16527a84e90017d5482c"},
"title":"hf"

{"_id":{"$oid":"5eee7b31c16b3d0017ee4dbb"},
"title":"pineapple cake"

**Comment by WDI-IT** [comment]
what is your name?

**Comment by deeptikinger** [comment]
My name is Deepti

**Pull request closed without merging**
